<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>ЭС ПОДБОР АВТОМОБИЛЯ</title>
</head>
<body style="height: 100%; display: grid;grid-template-rows: repeat(5, 30px);grid-template-columns: repeat(5, 1fr)">
    <a href="/start" style="border-style: solid; border-width: 1px; display: flex; justify-content: center; align-items: center; grid-row: 3; grid-column: 3; border-radius: 7px; width: 66%; text-decoration: none; font-size: larger">Начать</a>

</body>
</html>